### ISSUE TITLE
Implement contact picker across all pages dealing with contacts

### ISSUE THREAD

**Issue by rockfordlhotka** [HTBox/MobileKidsIdApp#165]
- [ ] Android
- [ ] iOS
- [ ] UWP
- [ ] WP8

This affects a number of pages which currently display the ContactId and a button allowing the user to select a contact. Those pages should actually display the contact name pulled from the real contact, and the contact select button should allow the user to select a contact from the device.

I had a conversation with James Montemagno from Xamarin last week about this scenario. He recommends using a different approach entirely - where our app asks the device to display the standard/default contact manager to allow the user to select the contact.

Unfortunately it doesn't sound like there's a pre-existing plugin to do this, but it also sounds overall much easier, and a better user experience, than trying to implement our own contact picker for each platform.

**Comment by rockfordlhotka** [comment]
I had a conversation with James Montemagno from Xamarin last week about this scenario. He recommends using a different approach entirely - where our app asks the device to display the standard/default contact manager to allow the user to select the contact.

Unfortunately it doesn't sound like there's a pre-existing plugin to do this, but it also sounds overall much easier, and a better user experience, than trying to implement our own contact picker for each platform.

**Comment by bseebacher** [comment]
So if I'm reading this correctly, James is telling us not to use his plugin?

https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/Contacts

**Comment by rockfordlhotka** [comment]
Yes, basically he said he tried creating a more abstract wrapper over the Xamarin.Mobile API, but doesn't plan to maintain his wrapper.

More importantly we discussed our actual scenario and his opinion (which seems correct to me) is that we should tap into each platform's pre-existing contact picker feature rather than trying to pull the contacts directly at an API level. That way the user gets the contact picker for the device they are using, so they get a familiar experience, and we get back the id token for the chosen contact (which is what we want to store in the first place).

**Comment by bseebacher** [comment]
Sounds like the right approach to me. 

We'll just need to make sure to add the requisite housekeeping routines to make sure the contacts referenced by the stored ID value still exist on the device. (See also photo picking)

**Comment by rockfordlhotka** [comment]
Here's some info on the UWP contact picker:
https://msdn.microsoft.com/en-us/library/windows/apps/windows.applicationmodel.contacts.contactpicker.aspx?cs-save-lang=1&cs-lang=csharp#code-snippet-1

**Comment by bseebacher** [comment]
I just pulled up the iOS Simulator today and ran into this issue. Reverting to the last stable NuGet package version of Xamarin.Forms (2.2.0.45) got me past this for now, but I don't know the full consequences.

http://forums.xamarin.com/discussion/67752/method-cgrect-ctor-not-found-exception-after-upgrading-to-xamarin-forms-version-2-2-0-43

**Comment by bseebacher** [comment]
The iOS sample above references a deprecated iOS API (v8). Here's the successor API in iOS 9 and up. I assume we can use a similar technique to shell out to the native API bits.

https://developer.apple.com/library/ios/documentation/ContactsUI/Reference/ContactsUI_Framework/index.html#//apple_ref/doc/uid/TP40016207

**Comment by bseebacher** [comment]
I'm a bit out of my depth on this one. Maybe I'm missing something obvious...

Since this is a native function, I was planning on implementing platform-specific implementations of the various contact pickers in the platform projects, and then wire them into the core project as  DependencyService implementations. 

The problem here is that every example I've seen so far of this approach use dependencies that basically just provide data back to the core project to render. For example, there are a number of samples on reading the battery discharge status on the device, which is then surfaced in the Xamarin Forms UI. What I have not seen is an example where you "shell out" to a core native UI piece, poll the result of the interaction with it, and return the results back as the return type of a larger method call. 

It could be I'm not reading the intent and limits of DependencyService quite right, and need to think of a different approach. If the screen/screens that calls the contact picker were in the native projects, you'd be able to handle all the events/interactions with the native pieces. Do this enough, however, and pretty soon you've got three versions of this app.

Maybe someone with a little more Xamarin Forms-fu can point out a solution here...

**Comment by bseebacher** [comment]
So after thinking this over some more, I think I'll try taking this on as a custom rendered view instead of as a DependencyService. 

https://developer.xamarin.com/guides/xamarin-forms/custom-renderer/view/

**Comment by rockfordlhotka** [comment]
The only concern you should consider (I think) is that it is probably best to give the user a familiar feel when choosing contacts, so tapping into the native contact picker on each app probably provides that experience. Though perhaps that can be accomplished with custom rendered views?

**Comment by bseebacher** [comment]
I'm still with you on the native experience being preferable. I'm thinking that the custom rendered view will be nothing more than a thin wrapper that invokes and handles events (selection, cancel, etc.) from the native picker controls on the various platforms. There are some lifecycle event concerns that I haven't quite figured out how to the other way.
