### ISSUE TITLE
Update to Xamarin Forms 3.0

### ISSUE THREAD

**Issue by rockfordlhotka** [HTBox/MobileKidsIdApp#221]

**Comment by bseebacher** [comment]
Side note - there are quite a few package updates pending in the current source code. Pulling them in breaks the build - probably something we should iron out before the hackathon. 

<img width="297" alt="image" src="https://user-images.githubusercontent.com/7266719/41238451-957a4cdc-6d5b-11e8-816b-d500741ac9b9.png">

**Comment by rockfordlhotka** [comment]
Totally agree - there've been substantial updates to a lot of packages beyond Xamarin. I planned to do these package updates prior to the codeathon, but if you want to take a run at it I'm happy with that too 😄

**Comment by bseebacher** [comment]
If my Xamarin skills ramp up a bit while I'm taking a stab at #210, maybe I will. Right now, I'm just happy that I can get a working build.

BTW, this solution less the UWP project loads and runs great on VS for Mac. I'm doing some iOS styling, and it saves on the debugger round trip.

**Comment by bseebacher** [comment]
Since I'm feeling adventurous, I decided to branch the current reference build and try updating all the packages, including Xamarin Forms 3. It's a bit early, but here are some highlights:

* The main App.xaml view in the core project appears not to be compatible with v3. The build throws this error: 'The type 'Application' does not support direct content.'. I assume this means there's a new way to set up the root views, but since I only dabble in Xamarin, I'll need to hit the books to figure that out. (Maybe @rockfordlhotka knows better here.)
* The Windows Azure mobile authentication library has also taken on a major version update. I think our calls are coded against an extension library that I haven't yet found the equivalent for. Once I dig that up, I assume things will just work, but we may find there's more to do here.
* I had to add the .NET Standard package to the device builds to support CSLA. No surprises there.

Unless the App.xaml thing turns out to be the first sign of larger UI changes, I don't see anything too crazy here; just your standard old .NET project package update fun.

**Comment by tlhotkamcm** [comment]
Thank you Brian!

**Comment by bseebacher** [comment]
Update here: I now have a very rough build going on iOS and Android. I had to comment out the Azure login services (API changes) and the Android contact picker dependency service (plugin no longer maintained, see #224). I haven't started on UAP yet. Other than this, things are generally working - we'll just keep hacking.

You can see my work in progress here.
https://github.com/bseebacher/MobileKidsIdApp/tree/221

**Comment by bseebacher** [comment]
I now have an updated build for UWP, but it will need a second look from @rockfordlhotka, as I had to pull CSLA-Core from the project in order to get it to build. When I had both this and CSLA-XamarinForms, the build throws this error:

![image](https://user-images.githubusercontent.com/7266719/41495025-84923836-70e3-11e8-948e-82560fb87fc4.png)

The CSLA-Core free build produced no explosions in my very limited testing, but I'm pretty sure that's not going to hold. Luckily, I think @tlhotkamcm knows the guy who writes this library :)

Code here:
https://github.com/bseebacher/MobileKidsIdApp/tree/221

**Comment by rockfordlhotka** [comment]
There's now CSLA-Core-NS that supports all platforms _except_ full .NET on the server. The CSLA-Core package _only_ supports full .NET on the server.

(and wouldn't be necessary except for an obscure bug in full .NET when supporting netstandard 😢 )

**Comment by rockfordlhotka** [comment]
@bseebacher HOLD OFF ON DOING MORE WORK for the moment - I'm going to convert all the projects to netstandard 2.0, which is kind of major surgery, but gets us the ability to use the latest frameworks and VS tool goodness.

**Comment by bseebacher** [comment]
Sounds good, @rockfordlhotka . I took a glance at doing that, but I didn't get very far.
