### ISSUE TITLE
Update Azure authentication implementation

### ISSUE THREAD

**Issue by rockfordlhotka** [HTBox/MobileKidsIdApp#228]
After upgrading to netstandard 2.0, the Azure authentication code we were using is no longer available. We need to replace that functionality (marked with TODO comments) with an updated implementation.

**Comment by bseebacher** [comment]
Before we re-implement this, it would be worth having a look again at local authentication strategies so that we can eliminate a cloud dependency.  It would also be pretty cool to implement this as a Touch ID login using the device (if available).

https://blog.xamarin.com/securing-your-app-with-touch-id/

**Comment by rockfordlhotka** [comment]
Replaced by #260
