### ISSUE TITLE
Replace provider based authentication with a local password

### ISSUE THREAD

**Issue by rockfordlhotka** [HTBox/MobileKidsIdApp#260]
Our original concept had some reasons for supporting Facebook and Twitter and such, but as requirements have evolved these aren’t necessary and now just add complexity.

A better answer is to use a pass phrase or pin. That value will directly be the encryption key for the data, which should be more secure.

**Comment by DanKline** [comment]
Hi Rocky.  I'm looking at this and am probably out of my core strengths, but were you thinking asymmetrical key encryption and using something similar to this.  I'd like to make sure we are looking down the same path before I start so that if I get stuck or not finished, someone can continue with the pieces.
(https://dzone.com/articles/xamarin-android-asymmetric-encryption-without-any)

**Comment by rockfordlhotka** [comment]
Hey Dan, sorry, didn't see your comment until just now. 

I'm almost done with the changes. We already have all the encryption stuff in the code - this is just a change to replace the use of FB/twitter/etc. with a simple password entry by the user.

**Comment by rockfordlhotka** [comment]
I am reopening this, as I think we need to detect the first-run scenario and confirm the user's password. Since there's no recovery of a lost pw (it is the encryption key after all), we can't allow a simple typo to block the user.
