### ISSUE TITLE
Friends - Multiple contact screens appear, which leads to a crash

### ISSUE THREAD

**Issue by Butteri** [HTBox/MobileKidsIdApp#302]
In the Friends section, if the user taps the + button, then taps the Back icon on the screen or the phone, multiple contact screens will appear, and the app will crash after closing them.

Steps to Reproduce:

1) Select My Kids.
2) Select an existing entry from the Child List.
3) Tap Friends.
4) The Contact screen appears.
5) Either tap the Back icon on the screen or the back button on the phone.

Expected Result:
The user is returned to the Friends screen.

Actual Result:
Another Contact screen appears (up to 2-4 of them total).  If the user continues to press the back button, the app will crash.

Tested on Samsung Galaxy S8 version 8.0.0.

**Comment by rockfordlhotka** [comment]
Maybe related to #288

**Comment by rockfordlhotka** [comment]
@brunck I'm hoping you can look at this to see if it is something with the contact picker itself, or with how it is being invoked.

When I click "+" on Android or Win10 in the Friends page the contact picker shows up 2 times (at least). You can see this on Android by 

1. Click "+" to get a picker
1. Back out of the picker
1. You are still on a picker (on my emulator I can see the top one close to reveal the second one)
1. Close the second one 
1. Then click "+" again and the app crashes

**Comment by brunck** [comment]
This specific problem doesn't seem to be reproducible (on iOS), but it still isn't working. 

You can bring up the Contact picker, but selecting a contact doesn't do anything; nothing is added to the Friends screen. This is also visible on the Basic Info screen, where you can select a Contact but nothing changes no matter what Contact you select.

Even worse, if you do this on the Friends screen, but you Cancel out of the picker instead of picking one, then navigate back, the second child in the Childprofiilelist (if there is one) is DELETED completely! 
Navigating back to the landing page and then back to My Kids doesn't restore the 2nd in the list as it does when picking photos; see #332 which is similar but doesn't delete the 2nd item.
